# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    goals: 'clean test'
    options: '-Pintegration'
- script: |
    mvn package -DskipTests=true

# Publish jars as artifact
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-cli'
    targetPath: ./openvalidation-cli/target/openvalidation.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-oapi-cli'
    targetPath: ./openvalidation-openapi-generator/target/ov-openapi-generator-cli.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-antlr'
    targetPath: ./openvalidation-antlr/target/openvalidation-antlr-1.0-SNAPSHOT.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-common'
    targetPath: ./openvalidation-common/target/openvalidation-common-1.0-SNAPSHOT.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-core'
    targetPath: ./openvalidation-core/target/openvalidation-core-1.0-SNAPSHOT.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-generation'
    targetPath: ./openvalidation-generation/target/openvalidation-generation-1.0-SNAPSHOT.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'openvalidation-openapi-generator'
    targetPath: ./openvalidation-openapi-generator/target/openvalidation-openapi-generator-1.0-SNAPSHOT.jar
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'openvalidation-parent-pom'
    targetPath: ./pom.xml

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-rest'
    targetPath: ./openvalidation-rest/target/ov-rest.jar

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-docker'
    targetPath: ./dockerfile
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'releaseartifacts-kubernetes'
    targetPath: ./kubernetes-deployment.yaml

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'rest-docker'
    targetPath: ./openvalidation-rest/src/main/docker/dockerfile_rest
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'rest-kubernetes'
    targetPath: ./openvalidation-rest/src/main/docker/kubernetes-deployment_rest.yaml

